[camera]
mouse_sensitivity = 1e-3

[camera.fixed_angle]
min_distance = 5.0
max_distance = 20.0
zoom_speed = 0.5
rotation_smoothing = 45.0
translation_smoothing = 50.0

[camera.first_person]
translation_smoothing = 50.0
rotation_smoothing = 45.0
most_acute_from_above = 0.62831855 # TAU / 10.
most_acute_from_below = 0.8975979 # TAU / 7.

[camera.third_person]
translation_smoothing_going_closer = 100.0
translation_smoothing_going_further = 50.0
rotation_smoothing = 45.0
most_acute_from_above = 0.62831855 # TAU / 10.
most_acute_from_below = 0.8975979 # TAU / 7.
min_distance = 0.01
max_distance = 10.0
zoom_speed = 0.5
min_distance_to_objects = 1e-2

